---
# Note: this required ansible-galaxy install Azure.azure_modules

# create all the items necessary to make the VM
- name: "Create resource group"
  hosts: localhost
  gather_facts: no
  tasks:
  - name: "provision public ip address"
    import_role:
      name: openshift_azure
      tasks_from: provision_instance.yml

- name: update OS and install packages
  hosts: azure
  gather_facts: yes
  remote_user: "{{ openshift_azure_vm_admin_username }}"
  become: True
  tasks:
  - name: lay down yum certs
    copy:
      content: "{{ item.content }}"
      dest: "/var/lib/yum/{{ item.name }}"
    with_items:
    - name: client-cert.pem
      content: "{{ yum_client_cert_contents }}"
    - name: client-key.pem
      content: "{{ yum_client_key_contents }}"

  - name: setup yum repositories
    import_role:
      name: openshift_repos

  - name: update OS
    import_role:
      name: os_update_latest
    vars:
      os_update_latest_reboot: True

  ## Cleanup yum repositories and certificates
  - name: remove yum repositories
    yum_repository:
      state: absent
      file: "{{ item.name | default(item.id) }}"
      name: "{{ item.name | default(item.id) }}"
    with_items: "{{ openshift_additional_repos }}"

  - name: remove our yum client certs
    file:
      state: absent
      path: "/var/lib/yum/{{ item.name }}"
    with_items:
    - name: client-cert.pem
    - name: client-key.pem
  ## End cleanup yum repositories and certificates

# NOTE: this isn't available until ansible 2.5
# https://github.com/ansible/ansible/pull/32589
# installed from https://releases.ansible.com/ansible/rpm/nightly/devel/epel-7-x86_64/
- name: Create image
  hosts: localhost
  tasks:
  - name: deprovision and prepare image
    import_role:
      name: openshift_azure
      tasks_from: create_image_from_vm.yml
    vars:
      openshift_azure_vm_host: "{{ groups['azure'][0] }}"
