---
- hosts: localhost
  gather_facts: no
  tasks:
  - import_tasks: tasks/provision_instance.yml
    vars:
      image_prefix: "{{ openshift_azure_input_image_prefix }}"
      image_resource_group: "{{ openshift_azure_input_image_ns }}"

- hosts: nodes
  tasks:
  - set_fact:
      openshift_additional_repos: "{{ azure_base_repos[ansible_distribution] }}"

  - import_tasks: tasks/yum_certs.yml

  - import_role:
      name: os_update_latest
    vars:
      os_update_latest_reboot: True

  - import_tasks: tasks/remove_yum.yml

  - command: waagent -deprovision+user -force
    args:
      chdir: /

- hosts: localhost
  gather_facts: no
  tasks:
  - import_tasks: tasks/create_image_from_vm.yml
    vars:
      image_prefix: "{{ openshift_azure_output_image_prefix }}"
      image_resource_group: "{{ openshift_azure_output_image_ns }}"
      image_tags:
        root_image: "{{ input_image.stdout | from_json }}"
        kernel: "{{ hostvars[groups['nodes'][0]]['ansible_kernel'] }}"

- import_playbook: deprovision.yml
