---
- azure_rm_resourcegroup:
    name: "{{ openshift_azure_resource_group_name }}"
    location: "{{ openshift_azure_resource_location }}"

- azure_rm_virtualnetwork:
    name: vnet
    resource_group: "{{ openshift_azure_resource_group_name }}"
    address_prefixes:
    - 192.168.0.0/16

- azure_rm_subnet:
    name: subnet
    resource_group: "{{ openshift_azure_resource_group_name }}"
    virtual_network: vnet
    address_prefix: 192.168.0.0/24

- command: az image list -g "{{ image_resource_group }}" -o json --query "[?starts_with(name, '{{ image_prefix }}-') && tags.valid=='true'].name | sort(@) | [-1]"
  register: input_image

- command: az image show -g "{{ image_resource_group }}" -n "{{ input_image.stdout | from_json }}" -o json --query tags
  register: input_image_tags

- azure_rm_virtualmachine:
    name: vm
    resource_group: "{{ openshift_azure_resource_group_name }}"
    vm_size: Standard_D4s_v3
    image:
      name: "{{ input_image.stdout | from_json }}"
      resource_group: "{{ image_resource_group }}"
    os_type: Linux
    storage_blob_name: vm
    managed_disk_type: Standard_LRS
    data_disks: "{{ data_disks | default([]) }}"
    admin_username: cloud-user
    ssh_password_enabled: False
    ssh_public_keys:
    - path: "/home/cloud-user/.ssh/authorized_keys"
      key_data: "{{ openshift_azure_vm_ssh_public_key }}"
  register: vm

- add_host:
    groups: nodes
    name: "{{ vm.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    ansible_ssh_user: cloud-user
    ansible_become: True
