---
- file:
    state: absent
    path: "/var/lib/yum/{{ item.name }}"
  with_items:
  - name: client-cert.pem
  - name: client-key.pem
  when: ansible_distribution == "RedHat"

- yum_repository:
    state: absent
    name: "{{ item.name }}"
  with_items: "{{ openshift_additional_repos }}"
